apiVersion: v1
kind: Service
metadata:
 name: clusteripsvc
 namespace: todoapp
spec:
 type: NodePort
 selector:
   app: todoapp
 ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
     nodePort: 30001
